### PR TITLE
Made push and replace traversing safe.

### PR DESCRIPTION
**Pull request by neilmarietta**
* Added ViewUtils.waitForTraversingState.
* Wrap push and replace calls within a waitForTraversingState call.

### CODE REVIEW

**Comment by tomjhall** [comment]
This looks fine - my only problem is that the view stack has changed over so that push/pop operations are always going to happen - regardless of the current state. A user may want the operation to fail if the state is not what they expect (now we have a 'queued' operation that can't be undone). 

Ideally we want two operations - push as it is (reject if it isn't in the correct state) and push when safe - that queues this.

It seems that we can do this without any changes to the view stack. If we had a view stack helper (that has static methods) we could do this fairly easily:

class ViewStackOperations {
 ...

static void pushWhenIdle(@ NonNull ViewStack viewStack, int layout, ...) {
  ViewUtils.waitForTraversingState(... 
    void onTraversal() {
     viewStack.push(layout,...);
   }
}

**Comment by gtomek** [comment]
@tomjhall so what do you suggest? Shall we add ViewStackOperations helper class to this project?
What should be used in the example app? The pushWithIdle()? or just push() from ViewStack?
It seems to be a bit confusing for someone who doesn't know this library very well. 

Ideally we should have one method to call for one task/function and not too many options.
Something that will fix also ConcurrentModificationException and IllegalStateException: ViewStack is currently traversing

**Comment by tomjhall** [comment]
I would suggest having ViewStackOperations - and using (potentially) using this in the example app.

**Comment by neilmarietta** [comment]
Replaced by https://github.com/R3PI/Defrag/pull/26.

**Pull request closed without merging**
